### ISSUE TITLE
Crash upon opening a FITS file in MacOS Monterey 12.2.1

### ISSUE THREAD

**Issue by DBerke** [siyu6974/QuickLook.Plugin.FitsViewer#2]
Hello,

Just came across this app today, and it seems like exactly what I want. Unfortunately, on my system, it immediately and repeatably crashes whenever I try to open a FITS file with it, either through the menu or by dragging one onto the window. Pressing Spacebar on a FITS file also produces a message in the pop-up preview window saying "Extension CYo.QuickFits.FitsQucklook failed during preview of this document." I'm sure that's not very helpful, so let me know if I can provide any more useful system information. Thanks!

**Comment by siyu6974** [comment]
Hey DBerke, sorry I didn't see this message earlier. It would be very helpful if you can describe the FITS file you're trying to open, or if you can send it to me to analyze.
