### ISSUE TITLE
FITS file is flipped vertically compared to opening with Siril

### ISSUE THREAD

**Issue by howardgrams** [siyu6974/QuickLook.Plugin.FitsViewer#3]
Quicklook fitsviewer plugin displays fits files upside down compared to opening them with Siril.  This may or may not be related to ignoring ROWORDER: TOP-DOWN from the fits header.

Howard Grams

**Comment by siyu6974** [comment]
Yes exactly, I wan't aware of that header keyword when I started the project. I can have it fixed for the next release.

**Comment by howardgrams** [comment]
Fabulous!!  Looking forward to it.
